CREATE DATABASE IF NOT EXISTS matrix_hub;
CREATE DATABASE IF NOT EXISTS asistencia_db;
CREATE DATABASE IF NOT EXISTS inventario_db;
CREATE DATABASE IF NOT EXISTS turnos_db;
CREATE DATABASE IF NOT EXISTS oee_db;

GRANT ALL PRIVILEGES ON *.* TO 'matrix_user'@'%';
FLUSH PRIVILEGES;
